### ISSUE TITLE
Return type error with PHP version lower than 7.1 : void

### ISSUE THREAD

**Issue by PeaceSfiSh** [AMartinNo1/ama_t3_upgrade_assistant#31]
**Describe the bug**
While opening the backend module the following error appears:
`Return value of AMartinNo1\AmaT3UpgradeAssistant\Controller\ConfigurationController::mainAction() must be an instance of AMartinNo1\AmaT3UpgradeAssistant\Controller\void, none returned
`

Both actions in ConfigurationController have the return type 'void' declared.
Regarding the ext_emconf.php this extension should be compatible with TYPO3 version 7.6.0-9.5.99

Return type 'void' is available with PHP 7.1, but the lowest required version for TYPO3 7.6 is PHP 5.5.
You should add the minimum required PHP version to the 'ext_emconf.php'.

**Comment by AMartinNo1** [comment]
Thanks for the feedback. I will provide proper changes.

**Comment by AMartinNo1** [comment]
Recent days were quite busy. I will try to test it within the next two weeks and prepare a release. Probably on 6th February.

**Comment by AMartinNo1** [comment]
Here's a little update. Currently modify my T3 ext. dev workflow. With the new workflow it's easier to test.
